### ISSUE TITLE
error running the code

### ISSUE THREAD

**Issue by wooohoo666** [gatekeepr/aloscraper#1]
Hello when trying to run this for the first time i get the following error:

Traceback (most recent call last):
  File "downloader.py", line 187, in <module>
    main()
  File "downloader.py", line 135, in main
    doLogin(email, password)
  File "downloader.py", line 89, in doLogin
    pwfield = browser.find_elements_by_xpath(
IndexError: list index out of range

**Comment by threatlevelm1dn1ght** [comment]
I get the same error.

**Comment by balabambuz** [comment]
I fixed it using   
browser.find_element_by_name("email") 
browser.find_element_by_name("password")
in the mailfield & pwdfield In the doLogin function
